# The URL the site will be built for
base_url =  "https://dumasymptote.com"
#base_url =  "http://127.0.0.1:1111" #used for running locally as test
#theme info
theme = "terminimal"
title = "Dumasymptote"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
# this enables the tags function
taxonomies = [
    {name = "tags"},
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
accent_color = "green"
background_color = "dark"
logo_text="Dumasymptote"
logo_home_link="/"
page_titles=true
menu_items = [
    {name = "blog", url="$BASE_URL/blog"},
    {name = "law school", url="$BASE_URL/lawschool"},
    {name = "about", url="$BASE_URL/about/about"},
    {name = "tags", url = "$BASE_URL/tags"},
]
author = "Mark G"